### ISSUE TITLE
Extension not showing rendering option on right-clicking an image

### ISSUE THREAD

**Issue by rohanakut** [Shared-Reality-Lab/IMAGE-browser#162] opened 2022-02-14 20:51 UTC
The extension intermittently stops working and does not show the option of getting renderings on right-clicking the image. 

The following was the system on which the error occurred:
Browser: Chrome(Version 98.0.4758.80 (Official Build) (arm64))
Extension downloaded from nightly on 10th of February
Tested on Macbook Air(2020)

Reproducibility: The issue occurs intermittently and hence it is very difficult to reproduce this issue. The latest occurrence of this issue was while testing the kitchen image on the [IMAGE webpage](https://image.a11y.mcgill.ca/pages/tech.html). 

The following error is visible in the logs for the extension. This error could be the reason for the intermittent nature of this issue. 
<img width="850" alt="Screen Shot 2022-02-14 at 3 53 35 PM" src="https://user-images.githubusercontent.com/27781159/153944857-fdb32f18-de53-4a9f-8e76-009da4c3ed1a.png">

**Comment by sriGanna** [comment] 2022-02-14 20:53
I have a similar issue with the nightly version and custom builds (which work on Rayan's computer). These are screenshots of my errors in both chrome and edge
![image (4)](https://user-images.githubusercontent.com/16036636/153944697-962c89b9-35dc-44a8-af03-5c80639f9127.png)

![image](https://user-images.githubusercontent.com/16036636/153944711-1653d069-5d0e-409b-bf6d-9c9bbee5cc39.png)

**Comment by jeffbl** [comment] 2022-02-14 22:45
Copied from slack, following up on meeting for this issue after tech-arch:

There was a fix to the extension that should have been live in the build available last Thursday, Feb10. If you're using an older version of the extension, it had numerous issues involving the settings page and the [IMAGE menu item disappearing entirely](https://github.com/Shared-Reality-Lab/IMAGE-browser/issues/145). This likely explains @sriGanna seeing this issue. However, @rohanakut indicates he installed the extension using the nightly build last Thursday, and saw this issue, even though the fix should have been in. After sorting out the previous issue, we all loaded the nightly available today (Monday), and running against unicorn, were unable to reproduce this issue. I'm continuing to try and reproduce. If anyone else can as well, that would be very helpful - scream loudly on #testing if you reproduce this!

**Comment by jeffbl** [comment] 2022-02-14 22:46
Leaving open and blocking Open Beta milestone to see if anyone can reproduce this.

**Comment by jeffbl** [comment] 2022-02-15 03:24
Using the nightly extension from afternoon of 20220214, I cannot reproduce this, despite toggling the Developer Model option repeatedly, switching tabs, trying multiple graphics, etc.

**Comment by Cybernide** [comment] 2022-02-15 03:48
I'm not getting this either. Is there anybody else who can?

**Comment by jeffbl** [comment] 2022-02-15 21:29
Moved this to next milestone since we have not been able to reproduce on latest extension.

**Comment by jeffbl** [comment] 2022-02-18 16:37
Closing as not reproducible. Assumption is that this was indeed fixed last week in #145. @rohanakut if you do manage to reproduce it with a current build, please re-open.

**Closed by jeffbl** 2022-02-18 16:37 UTC
